name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ryanwinter/arm-none-eabi-gcc@v2.0.4
      with:
        release: '10.3-2021.10' # The arm-none-eabi-gcc release to use.

    - name: Install dependencies
      run: make
